In [2]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [4]:
#Solution 1
dietstudy = pd.read_csv("dietstudy.csv")
dietstudy.head()
#Parameters taken into considerations for weights are initial weight(wgt0) and final weight(wgt4).
#Parameters taken into considerations for triglyceride levels are initial triglyceride level(tg0) and final triglyceride level(tg4).

patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

In [6]:
#For Weights
stats.ttest_rel(a=dietstudy.wgt0,b=dietstudy.wgt4)
#here pvalue is 1.137689414996614e-08 which is less than 0.05

Ttest_relResult(statistic=11.174521688532522, pvalue=1.137689414996614e-08)

In [7]:
#For triglyceride levels
stats.ttest_rel(a=dietstudy.tg0,b=dietstudy.tg4)
#here pvalue is 0.24874946576903698 which is more than 0.05

Ttest_relResult(statistic=1.2000008533342437, pvalue=0.24874946576903698)

In [ ]:
step-4: Statistical Score:- T score

step-5: Decide:- 
        For weights
        as pvalue(1.137689414996614e-08)<0.05 which implies reject null hypothesis accept alternative hypothesis
        
        For triglyceride levels
        as pvalue(0.25)>0.05 which implies fail to reject null hypothesis reject alternative hypothesis
        

So, 
    In terms of Weights, the measurement before and after new diet is changed.
    In terms of Triglyceride levels, the measurement before and after new diet is not changed.

In [6]:
#Solution 2
creditPromo = pd.read_csv("creditpromo.csv")
creditPromo.head()

#Parameters taken into considerations are sales(dollars column) for new promotion and standard.

creditPromo_new_promo = creditPromo.copy()
creditPromo_new_promo = creditPromo_new_promo.loc[(creditPromo_new_promo["insert"]=="New Promotion"),["dollars"]]
#creditPromo_new_promo.head()

creditPromo_std = creditPromo.copy()
creditPromo_std = creditPromo_std.loc[(creditPromo_std["insert"]=="Standard"),["dollars"]]


In [7]:
# as we don't have an idea whether they are independent or not so we taking both the cases

#case 1
stats.ttest_ind(a=creditPromo_new_promo,b=creditPromo_std,equal_var=True)

Ttest_indResult(statistic=array([2.26042273]), pvalue=array([0.024226]))

In [8]:
#case 2
stats.ttest_ind(a=creditPromo_new_promo,b=creditPromo_std,equal_var=False)

Ttest_indResult(statistic=array([2.26042273]), pvalue=array([0.02422635]))

In [9]:
# Solution 3

#a) parameters taken into considerations are complete Seed_Yield_Plant variable of pollination dataframe.
pollination=pd.read_csv("pollination.csv")
pollination.head()

Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

In [10]:
stats.ttest_1samp(a=pollination.Seed_Yield_Plant,popmean=200)

Ttest_1sampResult(statistic=-2.3009121248548645, pvalue=0.032891040921283025)

In [12]:
#(b) Parameters taken into consideration are fruit weight (kg), seed yield/plant (g) and seedling length (cm) of 
#   natural pollination and hand pollination.

pollination_natural=pollination.copy()
pollination_natural=pollination_natural.loc[(pollination_natural["Group"]=="Natural"),]

pollination_hand=pollination.copy()
pollination_hand=pollination_hand.loc[(pollination_hand["Group"]=="Hand"),]

In [13]:
#case 1: comparing on the basis of fruit weight
stats.ttest_rel(a=pollination_natural.Fruit_Wt,b=pollination_hand.Fruit_Wt)

Ttest_relResult(statistic=-16.003484109505287, pvalue=6.420421224715851e-08)

In [15]:
#case 2: comparing on the basis of seed yield/plant
stats.ttest_rel(a=pollination_natural.Seed_Yield_Plant,b=pollination_hand.Seed_Yield_Plant)

Ttest_relResult(statistic=-16.80079294985747, pvalue=4.198813240596638e-08)

In [16]:
#case 3: comparing on the basis of seedling length
stats.ttest_rel(a=pollination_natural.Seedling_length,b=pollination_hand.Seedling_length)

Ttest_relResult(statistic=-2.9765905136151303, pvalue=0.015535315669362245)

In [19]:
#Solution 4: parameters taken into considerations are dvdscores on the basis of categories.
dvdplayer=pd.read_csv("dvdplayer.csv")
dvdplayer.head()

dvdscore_under_25 = dvdplayer.copy()
dvdscore_under_25=dvdscore_under_25.loc[(dvdscore_under_25["agegroup"]=="Under 25"),["dvdscore"]]

dvdscore_25_34 = dvdplayer.copy()
dvdscore_25_34=dvdscore_25_34.loc[(dvdscore_25_34["agegroup"]=="25-34"),["dvdscore"]]

dvdscore_35_44 = dvdplayer.copy()
dvdscore_35_44=dvdscore_35_44.loc[(dvdscore_35_44["agegroup"]=="35-44"),["dvdscore"]]

dvdscore_45_54 = dvdplayer.copy()
dvdscore_45_54=dvdscore_45_54.loc[(dvdscore_45_54["agegroup"]=="45-54"),["dvdscore"]]

dvdscore_55_64 = dvdplayer.copy()
dvdscore_55_64=dvdscore_55_64.loc[(dvdscore_55_64["agegroup"]=="55-64"),["dvdscore"]]

dvdscore_65_over = dvdplayer.copy()
dvdscore_65_over=dvdscore_65_over.loc[(dvdscore_65_over["agegroup"]=="65 and over"),["dvdscore"]]



In [20]:
stats.f_oneway(dvdscore_under_25,dvdscore_25_34,dvdscore_35_44,dvdscore_45_54,dvdscore_55_64,dvdscore_65_over)

F_onewayResult(statistic=array([6.99252696]), pvalue=array([3.08732491e-05]))

In [47]:
# Solution 5
sample_survey=pd.read_csv("sample_survey.csv")
sample_survey.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree    ...           agecat childcat news1 news2  news3  \
0     NaN     High school    ...         55 to 64    2-Jan    No    No     No   
1     NaN  Junior college    ...         25 to 34     None    No    No    Yes   
2    16.0     High school    ...         35 to 44    2-Jan    No    No     No   
3     NaN     High school    ...     Less than 25     None    No    No     No   
4     NaN        Bachelor    ...         35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [51]:
#(a) parameters taken into considerations are labour force status(wrkstat) & marital status(marital).
sample_survey_a=sample_survey.copy()

sample_survey_a.wrkstat.fillna(sample_survey_a.wrkstat.mode()[0])
sample_survey_a.marital.fillna(sample_survey_a.marital.mode()[0])
sample_survey_a.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree    ...           agecat childcat news1 news2  news3  \
0     NaN     High school    ...         55 to 64    2-Jan    No    No     No   
1     NaN  Junior college    ...         25 to 34     None    No    No    Yes   
2    16.0     High school    ...         35 to 44    2-Jan    No    No     No   
3     NaN     High school    ...     Less than 25     None    No    No     No   
4     NaN        Bachelor    ...         35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [53]:
crossTab = pd.crosstab(sample_survey_a.wrkstat, sample_survey_a.marital, margins = True)
crossTab

marital                  Divorced  Married  Never married  Separated  Widowed  \
wrkstat                                                                         
Keeping house                  25      200             35         13       55   
Other                          12       16             14          4        8   
Retired                        53      168             17          6      150   
School                          7        9             60          2        1   
Temporarily not working         9       23             11          1        2   
Unemployed, laid off           10       13             32          0        3   
Working full time             295      778            392         58       44   
Working part-time              35      138            102          9       20   
All                           446     1345            663         93      283   

marital                   All  
wrkstat                        
Keeping house             328  
Other                      54  
Retired                   394  
School                     79  
Temporarily not working    46  
Unemployed, laid off       58  
Working full time        1567  
Working part-time         304  
All                      2830

In [54]:
stats.chi2_contingency(observed=crosstab)

(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [ ]:
step-4: Statistical value: Chi2 value

step-5: Decide:- As pvalue(7.424404099753273e-15)<0.05 which implies reject null hypothesis accept alternative hypothesis.

So, there is a relationship in between labour force status with marital status

In [56]:
#(b) parameters taken into consideration are educational qualification(sample_survey.degree) and marital status(sample_survey.marital).
sample_survey_b=sample_survey.copy()

sample_survey_b.degree.fillna(sample_survey_b.degree.mode()[0])
sample_survey_b.marital.fillna(sample_survey_b.marital.mode()[0])


crosstab = pd.crosstab(sample_survey_b.degree,sample_survey_b.marital,margins=True)
crosstab

marital         Divorced  Married  Never married  Separated  Widowed   All
degree                                                                    
Bachelor              58      251            129         12       28   478
Graduate              29      123             41          3        9   205
High school          241      686            367         58      148  1500
Junior college        45      108             46          3        6   208
LT High school        70      174             77         17       92   430
All                  443     1342            660         93      283  2821

In [57]:
stats.chi2_contingency(observed=crosstab)

(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [58]:
#(c)-1 Is happiness is driven by marital status?
#Parameters taken into consideration are happiness(sample_survey.happy) and marital status(sample_survey.marital)
sample_survey_c1=sample_survey.copy()

sample_survey_c1.happy.fillna(sample_survey_c1.happy.mode()[0])
sample_survey_c1.marital.fillna(sample_survey_c1.marital.mode()[0])


crosstab=pd.crosstab(sample_survey_c1.happy,sample_survey_c1.marital,margins=True)
crosstab

marital        Divorced  Married  Never married  Separated  Widowed   All
happy                                                                    
Not too happy        72       71            108         30       59   340
Pretty happy        278      684            426         49      137  1574
Very happy           93      582            120         13       83   891
All                 443     1337            654         92      279  2805

In [59]:
stats.chi2_contingency(observed=crosstab)

(260.68943894182826,
 7.762777322980048e-47,
 15,
 array([[  53.6969697 ,  162.06060606,   79.27272727,   11.15151515,
           33.81818182,  340.        ],
        [ 248.58538324,  750.24527629,  366.98609626,   51.62495544,
          156.55828877, 1574.        ],
        [ 140.71764706,  424.69411765,  207.74117647,   29.22352941,
           88.62352941,  891.        ],
        [ 443.        , 1337.        ,  654.        ,   92.        ,
          279.        , 2805.        ]]))

In [ ]:
step-4: Statistical value: Chi2 value

step-5: Decide:- As pvalue(7.762777322980048e-47)<0.05 which implies rehect null hypothesis accept alternative hypothesis.

So, Happiness is driven by marital status.

In [60]:
#(c)-1 Is happiness is driven by earnings?
#Parameters taken into consideration are happiness(sample_survey.happy) and earnings(sample_survey.income)
sample_survey_c1=sample_survey.copy()

sample_survey_c1.happy.fillna(sample_survey_c1.happy.mode()[0])
sample_survey_c1.income.fillna(sample_survey_c1.income.mode()[0])


crosstab=pd.crosstab(sample_survey_c1.happy,sample_survey_c1.income,margins=True)
crosstab

income         $1000 TO 2999  $10000 - 14999  $15000 - 19999  $20000 - 24999  \
happy                                                                          
Not too happy              7              39              33              40   
Pretty happy              20             107             119             155   
Very happy                 5              44              26              50   
All                       32             190             178             245   

income         $25000 or more  $3000 TO 3999  $4000 TO 4999  $5000 TO 5999  \
happy                                                                        
Not too happy             113              9              9              6   
Pretty happy              888             11             13             18   
Very happy                571              4             10             11   
All                      1572             24             32             35   

income         $6000 TO 6999  $7000 TO 7999  $8000 TO 9999  LT $1000   All  
happy                                                                       
Not too happy             14             12              9        11   302  
Pretty happy              13             21             30        13  1408  
Very happy                 6             14             19        11   771  
All                       33             47             58        35  2481

In [ ]:
Hypothesis Testing Stpes

step-1: Identify the problem:- Is happiness is driven by earnings?
        
step-2: Describe the hypothesis:
        Ho: Observed values == Expected Values
            (Variables are not influencing each other)
        Ha: Observed values <> Expected Values
            (Variables are influencing each other)
            
step-3: Statistical test: Chi square test because we are finding the relationship between two categorical variables.

In [61]:
stats.chi2_contingency(observed=crosstab)

(178.95053061216427,
 7.234749067043371e-21,
 36,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))